version: '3.8'

services:
  smee:
    image: node:16  # Smee requires Node.js
    container_name: smee
    restart: always
    command: npx smee --url https://smee.io/FhpqJU8lBASdjgq --path / --port 3000
    ports:
      - "3000:3000"  # Expose port 3000 for smee
    networks:
      - bot-network

  app:
    image: python:3.11  # Use Python 3.11
    container_name: app
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app  # Set the working directory to /app
    ports:
      - "3000:3000"  # Expose port 3000 for the app
    depends_on:
      - smee
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge